apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app.kubernetes.io/name: {{ include "lawfirm.fullname" . }}-db
    {{- include "lawfirm.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "lawfirm.fullname" . }}-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
